server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/store
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
#    dbcp2:
#      driver-class-name: com.mysql.jdbc.Driver
#      initialSize: 1
#      minIdle: 1
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.store.lucky.user.model
  config-location: classpath:mybatis.xml

#debug: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
